### ISSUE TITLE
Math/Modint

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#12]

**Comment by terry-u16** [comment]
`ModInt`もどのように実装するかちょっと悩ましいですね。
複数Modへの対応として、叩き台としていくつか案だけ考えてみました。

1. 定数Modを返すインターフェースを用意して、型引数として`struct`を差し込む
2. `static`変数でModを設定する
3. 構造体のメンバーとしてModを持たせる

```C#
interface IMod
{
    uint Mod { get; }
}

readonly struct Mod1000000007 : IMod
{
    public uint Mod => 1000000007;
}

/// <summary>
/// 案1：定数Modを返すインターフェースを用意して、型引数としてstructを差し込む
/// </summary>
readonly struct ModIntA<T> where T : struct, IMod
{
    public uint Value { get; }

    public ModIntA(long value)
    {
        var m = value % default(T).Mod;
        // ...
    }
}

/// <summary>
/// 案2：static変数でModを設定する
/// </summary>
readonly struct ModIntB
{
    public uint Value { get; }
    public static uint Mod = 1000000007;

    public ModIntB(long value)
    {
        var m = value % Mod;
        // ...
    }
}

/// <summary>
/// 案3：構造体のメンバーとしてModを持たせる
/// </summary>
readonly struct ModIntC
{
    public uint Value { get; }
    public uint Mod { get; }

    public ModIntC(long value, uint mod)
    {
        Mod = mod;
        var m = value % mod;
        // ...
    }
}
```

それぞれのメリット・デメリットとしては、

### 案1
メリット
- 同時に複数Modの使用が可能
- 構造体サイズが4byteで済む
- 異なるMod同士に対して型チェックが働く
- 構造体のジェネリックが展開されるためModがコンパイル時定数扱いされ、剰余演算が高速になる？（未検証）

デメリット
- 慣れていないと直感的でない（`ModInt`は低diff問題でもそれなりに使う機会が多いため気になる。よく使われるModについてラッパー等を用意するのは可）
- 毎回型引数を書くのが面倒（よく使われるModについてｒｙ）

### 案2
メリット
- 直感的に分かりやすい
- 構造体サイズが4byteで済む

デメリット
- 同時に複数Modの使用が不可能（競プロだとModは1つで十分なことが多いとはいえ……）

### 案3
メリット
- 直感的に分かりやすい
- 同時に複数Modの使用が可能

デメリット
- 異なるMod同士に対して型チェックが働かない
- 構造体サイズが8byteになる（コピーが遅くなる？64bit環境であれば関係ないかも？）

個人的に思い付けているところはここまでです。
ご意見頂ければ嬉しいです！

**Comment by key-moon** [comment]
ベンチマークを取ったんですが、案1 は定数展開されていそうなのでとても良さそうです。
複数 Mod は いろいろなアルゴリズムで必要になってきたりしますし、本家 ACL で行えていることを行えるようにしたいためこの方法がかなり理想的に思えます。

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19041
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=5.0.100-preview.7.20366.6
  [Host]     : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT


|                          Method |    Mean |    Error |   StdDev |
|-------------------------------- |--------:|---------:|---------:|
|                           Const | 3.175 s | 0.0631 s | 0.1054 s |
|         ModInterfaceStaticField | 8.920 s | 0.1750 s | 0.2454 s |
|          ModInterfaceStaticProp | 7.443 s | 0.1226 s | 0.1087 s |
|         ModInterfaceWithDefault | 2.953 s | 0.0384 s | 0.0320 s |
| AssignedModInterfaceWithDefault | 5.103 s | 0.0296 s | 0.0247 s |

<details><summary>code</summary><div>

```cs
public class ModTest
{
    const int MOD = 314;
    [Benchmark]
    public void Const()
    {
        long res = 0;
        for (int i = 0; i < int.MaxValue; i++)
        {
            res += i % MOD;
        }
    }
    [Benchmark]
    public void ModInterfaceStaticField()
    {
        long res = 0;
        for (int i = 0; i < int.MaxValue; i++)
        {
            res += i % Mod<Mod314>.ModField;
        }
    }
    [Benchmark]
    public void ModInterfaceStaticProp()
    {
        long res = 0;
        for (int i = 0; i < int.MaxValue; i++)
        {
            res += i % Mod<Mod314>.ModProp;
        }
    }
    [Benchmark]
    public void ModInterfaceWithDefault()
    {
        long res = 0;
        for (int i = 0; i < int.MaxValue; i++)
        {
            res += i % (default(Mod314).Mod);
        }
    }
    static int Mod = default(Mod314).Mod;
    [Benchmark]
    public void AssignedModInterfaceWithDefault()
    {
        long res = 0;
        for (int i = 0; i < int.MaxValue; i++)
        {
            res += i % Mod;
        }
    }
}

readonly struct Mod314 : Mod<Mod314>
{
    public int Mod => 314;
}

interface Mod<T> where T : struct, Mod<T>
{
    int Mod { get; }
    public static int ModField = default(T).Mod;
    public static int ModProp => default(T).Mod;
}
```　
</div></details>

**Comment by terry-u16** [comment]
ベンチマークありがとうございます……！ちゃんとコンパイラが頑張ってくれてそうですね。
この方針でちょっと書いてみますので、少々お待ちください。

**Comment by terry-u16** [comment]
C++版と同じく、内部では`int`, `long`ではなく`uint`, `ulong`で値を持たせることにしたいと思います。（mod 1e9+7のケースで剰余演算が2割弱ほど高速だったため）

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1082 (1909/November2018Update/19H2)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.1.300
  [Host]     : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT
  DefaultJob : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.22101), X64 RyuJIT


|            Method |     Mean |    Error |   StdDev |
|------------------ |---------:|---------:|---------:|
|       MultiplyInt | 10.185 s | 0.0146 s | 0.0129 s |
|  MultiplyIntConst |  3.320 s | 0.0081 s | 0.0072 s |
|      MultiplyUInt |  8.410 s | 0.0280 s | 0.0262 s |
| MultiplyUIntConst |  2.797 s | 0.0050 s | 0.0047 s |

<details>
<summary>Code</summary>

```C#
public class ModIntDivTest
{
    const int ModIntConst = 1000000007;
    const uint ModUIntConst = 1000000007U;

    int _modInt = ModIntConst;
    uint _modUInt = ModUIntConst;

    [Benchmark]
    public long MultiplyInt()
    {
        long a = 1L;
        for (int i = 1; i < ModIntConst; i++)
        {
            a *= i;
            a %= _modInt;
        }
        return a;
    }

    [Benchmark]
    public long MultiplyIntConst()
    {
        long a = 1L;
        for (int i = 1; i < ModIntConst; i++)
        {
            a *= i;
            a %= ModIntConst;
        }
        return a;
    }

    [Benchmark]
    public ulong MultiplyUInt()
    {
        ulong a = 1UL;
        for (uint i = 1U; i < ModUIntConst; i++)
        {
            a *= i;
            a %= _modUInt;
        }
        return a;
    }

    [Benchmark]
    public ulong MultiplyUIntConst()
    {
        ulong a = 1UL;
        for (uint i = 1U; i < ModUIntConst; i++)
        {
            a *= i;
            a %= ModUIntConst;
        }
        return a;
    }
}

```

</details>
