### ISSUE TITLE
規則について

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#18]
# コーディングスタイルについて
基本的に[MSDNのコーディング規約](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)に従います。Lintは導入しませんので、VisualStudioのコード整形機能を利用して下さい。
## 内部で使用する変数名について
基本的に、変数名はAtCoderによって提供されたC++の実装において、同等の場所にて命名されているものに従います。なお、`snake_case`と`camelCase`や`PascalCase`などは適宜変換するものとします。

# 提供されるインターフェイスについて
基本的に同名で同計算量のものを過不足なく提供するものとします。ただ、C#において同等の機能を表すものに対応させたい場合(IEnumerableやRange/Index等)は対応させて良いものとします。
ただ、C#の標準ライブラリでC++の標準ライブラリの同等の機能の命名と異なるもの(`size()`と`Length`や`Count`)については同様に置き換えることとします。

# バージョンについて
使用するC#の機能のバージョンはAtCoderのC#環境で使用できる最新バージョン、すなわち`C#8.0`とします。(コンパイラの一つである`Mono-MCS 6.8.0.105`においては[使用できない機能](https://github.com/mono/mono/issues/6854)もありますが、互換性のために残されているだけなので`CSC`又は`dotnet`のほうを用いてもらうということにします。)

# C#に存在しない機能を用いた実装について
see: #20

**Comment by key-moon** [comment]
Monoのサポートを切り捨てたい、そうするとAtCoderへの導入がNuGet入れるだけなのでかなり楽になるし、Hardware Intrinsicsによるネイティブ命令のサポートとかを使えて嬉しい。
Monoが優位に立つことってあるかな

**Comment by takytank** [comment]
EditorConfigファイルの追加はしないのでしょうか？
https://docs.microsoft.com/ja-jp/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019

個人的な事情ではあるのですが、普段使っている環境ではインデントがタブなため、うっかり混ぜてしまわないようにコーディングスタイルがソリューションに指定されていて自動整形出来ると助かります。

**Comment by key-moon** [comment]
C++ のコードを移植した後に規則に従って変換してもらって大丈夫な上、この規則はインターフェイス部分に影響するものではないので問題ないと考えています。(今規則に従ってない部分は、テストやCIを整備するときなどに直します。気になるなら直してもらってかまいません。)
ただ、この規則がコーディング規則として適格かどうかはわかりかねるので、もし .NET が特別な事情でこの規則を採用している、などがあるのならば変えても良いかなと思います。

**Comment by naminodarie** [comment]
> この規則がコーディング規則として適格かどうか

「そのプロジェクトでどう決めるか」でしかないので、適格かどうかはプロジェクトの判断によります。

https://github.com/dotnet/BenchmarkDotNet/search?q=%22private+static%22&unscoped_q=%22private+static%22
https://github.com/dotnet/BenchmarkDotNet/search?q=%22private+readonly%22&unscoped_q=%22private+readonly%22

たとえば、 BenchmarkDotNet は上記のルールを採用していません

> .NET が特別な事情でこの規則を採用している、などがあるのならば

上記のとおり、「プロジェクトでどう決めるか」でしかないので、採用している理由は「特別な事情」ではなく「個別の事情」です。

あくまで推測ですが、 .NET のランタイムなどは大規模な開発が必要なので命名ルールも厳しくしているのだと考えられます。そのようなルールに必ずしも縛られる必要はないかと思います。
