### ISSUE TITLE
テストについて

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#19]
NUnitとかを導入します 後で考えますが、CIとか回す予定です

**Comment by naminodarie** [comment]
#51 にコメントしました。

https://github.com/key-moon/ac-library-cs/pull/51#issuecomment-693514174

**Comment by key-moon** [comment]
テスト周りは詳しい事情を知らなかったので、WIP 版では NUnit を仮として使用しました。特に問題がないのであれば、主流な xUnit を使用して頂きたいです。
