### ISSUE TITLE
Expanderについて

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#21]
C#はプリプロセスでファイルを展開することができないため、依存フローの解析と展開をしないといけない。すでに依存フローの解析はRoslynを用いて[不十分ながらできている](https://gist.github.com/key-moon/2411fa3cb5acbab74714b0f92672db33)が、私だけで2週間で書き上げることができるかは微妙。

**Comment by naminodarie** [comment]
`using`をnamespaceの内側に書くようコード規約を定めれば、ファイルの中身を実行ファイルにまるごとコピペするだけで動くのでRoslyn使わずに済みそうだと思いました。

<details>
<summary>貼付け後のコード</summary>

```C#
using System;
using System.Collections.Generic;
using System.Text;
using AtCoder;

namespace AtCoderProgram
{
    static class Program
    {
        static void Main()
        {
            Console.WriteLine(AtCoder.Math.PowMod(123, 456, 789));
        }
    }
}


namespace AtCoder
{
    using AtCoder.Internal;
    using System.Diagnostics;
    public static partial class Math
    {
        /// <summary>
        /// <paramref name="x"/>^<paramref name="n"/> mod <paramref name="m"/> を返します。
        /// </summary>
        /// <remarks>
        /// <para>制約: 0≤<paramref name="n"/>, 1≤<paramref name="m"/></para>
        /// <para>計算量: O(log<paramref name="n"/>)</para>
        /// </remarks>
        public static long PowMod(long x, long n, int m)
        {
            Debug.Assert(0 <= n && 1 <= m);
            if (m == 1) return 0;
            Barrett barrett = new Barrett((uint)m);
            uint r = 1, y = (uint)InternalMath.SafeMod(x, m);
            while (0 < n)
            {
                if ((n & 1) != 0) r = barrett.Mul(r, y);
                y = barrett.Mul(y, y);
                n >>= 1;
            }
            return r;
        }
    }
}

namespace AtCoder.Internal
{
    public static partial class InternalMath
    {
        public static long SafeMod(long x, long m)
        {
            x %= m;
            if (x < 0) x += m;
            return x;
        }
    }
}

namespace AtCoder.Internal
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Runtime.Intrinsics.X86;
    using System.Runtime.Intrinsics;
    using System.Numerics;

    /// <summary>
    /// Fast moduler by barrett reduction
    /// <seealso href="https://en.wikipedia.org/wiki/Barrett_reduction"/>
    /// </summary>
    public class Barrett
    {
        public uint Mod { get; private set; }
        private ulong IM;
        public Barrett(uint m)
        {
            Mod = m;
            IM = unchecked((ulong)-1) / m + 1;
        }

        /// <summary>
        /// <paramref name="a"/> * <paramref name="b"/> mod m
        /// </summary>
        public uint Mul(uint a, uint b)
        {
            ulong z = a;
            z *= b;
            if (!Bmi2.X64.IsSupported) return (uint)(z % Mod);
            var x = Bmi2.X64.MultiplyNoFlags(z, IM);
            var v = unchecked((uint)(z - x * Mod));
            if (Mod <= v) v += Mod;
            return v;
        }
    }
}
```
</details>

**Comment by key-moon** [comment]
結局依存フローの解析はしないといけないのでRoslynは必要な気がします。

**Comment by key-moon** [comment]
- usingとかを変な書き方をしない(`using /**/ System;`とか)
- インデントがまとも
- 1ファイルで扱う`namespace`は一つのみ
- 一つのファイルに1ライブラリのみ

などの条件を整えれば、かなり雑にコンパイルエラーから依存関係を復元できそうです。

**Comment by naminodarie** [comment]
「本家が`#include <atcoder/all>`を全展開するのと同じように全ファイルを持ってくるだけの動作だったら」という意図でした。
使っているものだけとするならRoslynでの解析が必要ですね。

**Comment by AreTrash** [comment]
VisualSutdioのコードスニペットファイルを自動生成するとかはどうでしょうか？
VisualSutdio限定にはなってしまいますが、需要は結構あると思います。
https://docs.microsoft.com/ja-jp/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2019

ですが、依存関係の解消もいい感じにしたようなものを作るとなると、かなり厳しそうです。
Descriptionに依存するスニペットを追記してあげるぐらいしか思いつかないですね…

自動生成するスニペットの一例作ってみました。
https://gist.github.com/AreTrash/a33f7db98d3219a7771f87c7a9ada6a2

**Comment by key-moon** [comment]
現状インターフェイスに依存する設計が多くなっているので、スニペットを用いたコーディングではストレスがそこそこ生まれてしまう気はしますが、確かに需要がありそうですね。

コードについても昔書いたものがあるため、多少再利用できそうです。検討してみます。

https://github.com/key-moon/CSSnippetGenerator

**Comment by AreTrash** [comment]
確かにインターフェースばりばりのをペタペタするって考えると…。

競プロで使うだけが目的であれば、型を貼り付け時に入力できる設計にすると、
元コードは、インターフェースもジェネリックも要らないシンプルなコードになって、
ペタペタする量も必然的に減って一石二鳥な感じにはなりそうですが、
必然的に用途が限られてしまうので、これもこれでう～んという感じで難しいですね。

**Comment by key-moon** [comment]
元々ライブラリとして動く、つまり `Expander` ありきでの実装方針になっているので、それぞれのアルゴリズムについて特殊な処理をするとなるとかなり難しそうですね…

**Comment by AreTrash** [comment]
https://github.com/AreTrash/ac-library-cs/blob/AreTrash/show_diff/AtCoderLibrary/MaxFlow.cs#L7

using ailas ディレクティブで型を切り替える設計を試してみました。
7行目がその部分で、該当の型は組み込みの演算子を使うように変更しました。

```csharp
using __MFGraph_long__ = long;
```
のようにキーワードでは指定できないので、
```csharp
using __MFGraph_long__ = Int64;
```
となっています。
int型に変更したい場合は、手動で
```csharp
using __MFGraph_long__ = Int32;
```
と書き換えることになります。

これによって、本来の型の全てのメソッドを自由に使えるようになります。
書き換える際も、メソッドが存在している型なら自由に変更できます。

スニペットファイルの自動生成をしやすくするための、個人的な修正のつもりだったのですが、
このプロジェクトの実装としてみても、案外悪くなさそうです…

**Comment by key-moon** [comment]
これはプロジェクト内部の実装をいじらないといけないため、ライブラリとしては的確な実装ではないと思います。また、C++ の実装は複数の型で同じライブラリを扱えるようにしていたため、この実装だと移植として機能が不足してしまいます。

**Comment by AreTrash** [comment]
> 複数の型で同じライブラリを扱えるようにしていたため

これはたしかにクリティカルな問題ですね…

> プロジェクト内部の実装をいじらないといけない

これは、たとえば一つのファイルにコードをまとめてからコーディングするという方法をとった際は、
aliasをnamespace外にまとめておくようにしてあげれば、内部実装の変更とは違う感じになるかなと思っていましたが、
方法が限定されてしまう時点で、あまりよろしくないですね…

----

競プロで使うのがメインであれば、こんな方法でもいいかもと思ったのですが、
改めて考えてみると問題が結構ありますね。

稚拙な提案にも関わらず、意見していただきありがとうございます。すっきりしました！

**Comment by naminodarie** [comment]
#50 のExpanderを作成するまでに検討したことなど

## 言語はどうするか

本家C++ 版では Python が使われている。`#include` からファイルに置換する処理となっている。
C, C++ の `#include` はファイルと対応しているので、正規表現による文字列処理としてのパースで十分対応可能。

これに対して、C# では `namespace` がファイルと対応づいているわけではないので、なんらかの形で構文解析が必要となる。素直に **[Roslyn](https://docs.microsoft.com/ja-jp/dotnet/csharp/roslyn-sdk/) で解析するのがベターか**。

Roslyn なので .NET 系の言語で作る必要がある。

特にPowerShell Core はRoslynが同梱されるので、#30 で PowerShell 7.0 による実装を作成した。

### PowerShell でExpanderを実装する場合の課題

- PowerShell Core のインストールが必要
- Nuget で配布するライブラリに適用不能

前者はまだしも後者は非常に厳しいためClose。

C# のライブラリの解析をわざわざ VB や F# で書いてもしょうがないので C# での実装を検討することにした。

## ソースコードの取得方法について

Nuget でライブラリを配布するならば、DLLにソースコード文字列を埋め込むか外部のどこかしらに置くかのいずれかが必要。

どちらにしても労力は大差ないので、GitHub Actions でソースコードをコンパイル対象にした。また、埋め込む際に Roslyn で`using`ディクティブの分離したり、コードをminifyしたりファイル間の依存関係を解決したりする。これによって Expander ライブラリを用意すればソースコードが取得できるようになった。

## Expander の実装方法

`CallerFilePath` 属性をつけたデフォルト引数を用意すれば呼び出し元のファイルがわかるのでそのファイルを対象に Expand すれば自動で展開できるなと思った(WPF アプリなどの開発で `CallerMemberName` を使って `INotifyPropertyChanged` を実装するのと同じような気持ち)。

入力ファイルは取得できたが、Expand の動作で課題があった。

### SemanticModelを使った動作が遅い

コンパイルしているので当然だが非常に遅い。実行するたびに1秒以上かかるのは流石にストレスが大きい。

多少の誤判定を許容して `NameSyntax` で型名に一致するものがあれば良いということにしてSemanticModelを使わないモードを作った。

### Roslyn 関連のDLLの読み込みが遅い

`NameSyntax` にしたところで、Roslyn周りのDLL読み込みで200~300[ms] ほどかかっている。SemanticModel よりマシとは言え、もっと速くしたい。

結局、Roslyn を使わずに埋め込んだソースコードを全展開するモードも用意することにした。これならば、50[ms] 程度で動作が完了する。minify の効果で全展開しても 数十KB で済むので十分実用的かと考えた。

## 補遺

Expander は `CallerFilePath` で入力名を取得するのを基本としているが、外部から呼んでも良い。

下記の PowerShell コマンドを実行するとファイルが更新されたときに自動で "Combined.csx" が更新されるよう監視し続けてくれる

```powershell
$dir = "AtCoderLibrary.Expander\Expander.Sandbox\bin\Debug\netcoreapp3.1"
Add-Type -Path (Get-ChildItem "$dir\*.dll")

$ProgramPath = (Get-ChildItem "$dir\AtCoderLibrary.Expander\Expander.SandboxProgram.cs")

$OutputPath = (Join-Path $ProgramPath.DirectoryName "Combined.csx")


$lastUpdate = $null
while ($ProgramPath.Exists) {
    if ($lastUpdate -ne $ProgramPath.LastWriteTime) {
        $lastUpdate = $ProgramPath.LastWriteTime
        [AtCoder.Expander]::Expand($ProgramPath, $OutputPath)
        Write-Host "Update: $OutputPath at $lastUpdate"
    }
    Start-Sleep -Seconds 2
    $ProgramPath = (Get-ChildItem $ProgramPath)
}
```

入力ファイルが

**Comment by key-moon** [comment]
簡潔かつ詳細にまとめてくださり、本当にありがとうございます。参考にしつつ、現状のコードを詳細に読ませて頂きます。（外部プロセスから実行できる設計になっていることも把握できていませんでした。申し訳ないです）

DLL 読み込み周りですが、プロセスを常駐させれば気にならなくなるため、補遺のようなプログラムを動かすのであればその問題については解決できそうですね。

**Comment by naminodarie** [comment]
上記のサンプルでは PowerShell で DLL を読み込んで実行しているので、DLL への依存なしに外部プロセスから実行するならば

https://github.com/key-moon/ac-library-cs/pull/50/commits/09c60bbbadb52f391a77d5a69bd458a146072aa5

のように `dotnet` コマンドを叩く手法になるかと思います。

他にも呼び出し方はいろいろありそうだったので、サンプルをいくつか作ってみました。

https://github.com/naminodarie/ac-library-cs-expanders

**Comment by key-moon** [comment]
（恐らく DLL を動かした都合等で私の環境では power shell から expander の読み込みが上手く行かなかったのですが、）Expander による展開をコードに記すことが必須の実装ではないのが嬉しいです。コーディングの手法が限定されてしまうことが懸念点の一つだったので、一手法としてコードから展開用メソッドを呼ぶという手段を用意するという形になるなら一つの手法としてとても素晴らしいものだと私は感じました。

Expander ライブラリのインターフェイスに汎用的なものを用意することで、C# script 等の他の外部スクリプトやプログラムは Expander を叩けば良いだけにできるため、複数の手法を用意することによるメンテナンスのコストも膨れ上がらないのではと感じます（というか、そのような手法を取っていただけていると思います。）
なので、ファイルへの直での書き出しではなくメモリ上のオブジェクトとして受け取れるものなども公開されているとありがたいです。（実装の話になりますが、ExpandWriter あたりの引数に TextReader / TextWriter を追加することなんとかなりそうでしょうか。Stream 周りをコンストラクタに渡すのはあまり良くないデザインだと思うので代案があれば嬉しいです。ExpandWriter に Disposable をつけると良くなるでしょうか?）

**Comment by naminodarie** [comment]
Stream をコンストラクタに渡すのは TextWriter などで採用される非常にオーソドックスなデザインだと思います。

Stream を取り扱えるようにリファクタリングしました。
https://github.com/key-moon/ac-library-cs/pull/50/commits/ee9e3de4d2bbc8fe433476d1f55e2ffc761acb6d

**Comment by naminodarie** [comment]
一応完成はしました。
https://github.com/naminodarie/SourceExpander/

正直、これを管理外のリポジトリで通すのは気が重いので、Pull Requestは出さずに自分のリポジトリで開発を続行することにします。
nuget での名称被りを避けるために `ac-library-csharp` としています。
https://github.com/naminodarie/ac-library-csharp
https://www.nuget.org/packages/ac-library-csharp/
