### ISSUE TITLE
String/LCP Array

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#5]

**Comment by naminodarie** [comment]
`lcp_array`は`suffix_array`とセットで取り扱えるようにしたい気持ちがあります。
たとえば、`SuffixArray`クラスに`LcpArray`メソッドをつけるなど、C#版独自のクラスを返すメソッドがあっても良いのかなと思ったりしました。

**Comment by kzrnm** [comment]
上記のコメントについては #80 で
