### ISSUE TITLE
Operator に struct 制約を使用するべきか

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#59]
現状、Operator関係は

```cs
public class MFGraph<TValue, TOp>
    where TValue : struct
    where TOp : struct, INumOperator<TValue>
```

と、`struct` 制約が `TOp` についています。しかし、これは高速化のための制約なためなくても問題ありません。高速化のためのものをコードで強制するのに少し違和感があるので、`TOp` の `struct` 制約はないべきなのではないかと思います。

**Comment by terry-u16** [comment]
それは私も思いました。実用面でも例えば（するかどうかはさておき）継承ができない等のデメリットが生まれてしまいそうです。

**Comment by naminodarie** [comment]
賛成です。削除で良いと思います。

**Comment by takytank** [comment]
賛成ですが、単純に削除だと問題があります。
MaxFlow や Segtree 等において Operator を使用している部分は

```cs
 static readonly TOp op = default;
```

のようになっています。そのため、TOpに参照型が渡された場合、null参照になって死にます。
struct 制約を削除するのであれば、代わりに new() 制約を追加して、TOp のインスタンス作成部分を


```cs
static readonly TOp op = new TOp();
```

と変更する作業を同時に行う必要があります。

あとは、元々あんまり使用する気も無かったですが、 
https://github.com/key-moon/ac-library-cs/issues/33#issuecomment-691624765
の一部案にある

```cs
public TCap Multiply(TCap x, TCap y) => default(TCapOp).Multiply(x, y);
```

みたいな書き方は完全に避けた方がよくなりそうですね。

**Comment by kzrnm** [comment]
`default` が使えなくて困るので `struct` 制限はつけたままにしておきます。
