### ISSUE TITLE
McfGraphなどのグラフのクラスの命名について

### ISSUE THREAD

**Issue by universato** [kzrnm/ac-library-csharp#70]
## 本題

最大流はMFGraph、最小費用流はMcfGraphというクラス名になっています。  
この2つでクラス名の規則が異なっていて、気になったのでIssueを立てました。
他のDSUやSCCGraphを考えると、最小費用流をMCFGraphに変更するとスタイルが整合します。  

なお、本家AtCoderのC++ライブラリの命名の影響でMFGraphのような名称になっていると思いますが、  
本家のC++と異なり、アンダースコアのないキャメルケースは区切りがわかりにくく、略語が何なのかもわかりにくいです。   
以上を踏まえて、いっそクラス名とファイル名をSCC, MaxFlow, MinCostFlow等に統一してしまった方が、いいかもしれません。

|Lang|class       |file           |     |
|:---|:---        |:---           |:--- |
|C#  |DSU         |DSU            |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/DSU.cs)|
|C#  |**SCCGraph**|**SCCGraph**   |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/SCCGraph.cs)|
|C#  |**MFGraph** |**MaxFlow**    |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/MaxFlow.cs#L29)|
|C#  |**McfGraph**|**MinCostFlow**|[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/MinCostFlow.cs#L58)|
|C#  |Segtree     |Segtree        |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/Segtree.cs#L38)|
|C#  |LazySegtree |LazySegtree    |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/LazySegtree.cs#L51)|
|C#  |TwoSat      |TwoSat         |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/TwoSat.cs#L12)|
|C#  |ModInt      |ModInt         |[URL](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/Math/ModInt.cs#L72)|

## 参考

参考までに、他の言語の命名状況を貼っておきます。

|Lang   |SCC   |MaxFlow    |MinCostFlow     |
|:---   |:---     |:---    |:--- | 
|C++    |[scc_graph](https://github.com/atcoder/ac-library/blob/master/atcoder/scc.hpp#L12)|[mf_graph](https://github.com/atcoder/ac-library/blob/master/atcoder/maxflow.hpp#L14)     |[mcf_graph](https://github.com/atcoder/ac-library/blob/master/atcoder/mincostflow.hpp#L17) |
|C#     |[SCCGraph](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/SCCGraph.cs) |[MFGraph](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/MaxFlow.cs#L29)|[McfGraph](https://github.com/key-moon/ac-library-cs/blob/master/AtCoderLibrary/MinCostFlow.cs#L58) |
|Python |[SCCGprah](https://github.com/not522/ac-library-python/blob/master/atcoder/scc.py) |[MFGraph](https://github.com/not522/ac-library-python/blob/master/atcoder/maxflow.py#L4) |[MCFGraph](https://github.com/not522/ac-library-python/blob/master/atcoder/mincostflow.py#L5)|
|Rust   |[SccGraph](https://github.com/rust-lang-ja/ac-library-rs/blob/master/src/scc.rs) |[MfGraph](https://github.com/rust-lang-ja/ac-library-rs/blob/master/src/maxflow.rs#L7)     |[MinCostFlowGraph](https://github.com/rust-lang-ja/ac-library-rs/blob/master/src/mincostflow.rs#L16)|
|Go     |[SccGraph](https://github.com/monkukui/ac-library-go/blob/master/scc/scc.go#L6-L8) |---     |---|
|D      |[SccGraph](https://github.com/arkark/ac-library-d/blob/master/src/acl/scc.d#L7) |[MfGraph](https://github.com/arkark/ac-library-d/blob/master/src/acl/maxflow.d#L7)     |[McfGraph](https://github.com/arkark/ac-library-d/blob/master/src/acl/mincostflow.d#L7) |
|Java   |[SCC](https://github.com/NASU41/AtCoderLibraryForJava/tree/master/SCC)      |[MaxFlow](https://github.com/NASU41/AtCoderLibraryForJava/tree/master/MaxFlow)      |[MinCostFlow](https://github.com/NASU41/AtCoderLibraryForJava/tree/master/MinCostFlow)|
|Kotolin|[SCC](https://github.com/da-louis/ac-library-kt/blob/master/src/main/kotlin/jp/atcoder/library/kotlin/scc/SCC.kt#L6)      |[MaxFlow](https://github.com/da-louis/ac-library-kt/blob/master/src/main/kotlin/jp/atcoder/library/kotlin/maxFlow/MaxFlow.kt#L6)     |[MinCostFlow](https://github.com/da-louis/ac-library-kt/blob/master/src/main/kotlin/jp/atcoder/library/kotlin/minCostFlow/MinCostFlow.kt#L6) |
|Ruby   |[SCC](https://github.com/universato/ac-library-rb/blob/main/lib/scc.rb)      |[MaxFlow](https://github.com/universato/ac-library-rb/blob/main/lib/max_flow.rb)     |[MinCostFlow](https://github.com/universato/ac-library-rb/blob/main/lib/min_cost_flow.rb)|
|Crystal|[SCC](https://github.com/google/ac-library.cr/blob/master/atcoder/SCC.cr#L27)      |[MaxFlow](https://github.com/google/ac-library.cr/blob/master/atcoder/MaxFlow.cr#L28)     |MinCostFlow|

## 追記

[大文字の使用規則 \- Framework Design Guidelines \| Microsoft Docs](https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/capitalization-conventions?redirectedfrom=MSDN)

> パラメーター名を除くすべての識別子に使用される PascalCasing (パスカル ケース) 規則の場合、次の例に示すように各単語の最初の文字 (2 文字を超える頭字語を含む) を大文字にします。
> PropertyDescriptor HtmlTag

> 2 文字の頭字語には、特別な大文字と小文字の区別が使用され、次の識別子に示すように、両方の文字を大文字にします。
> IOStream

もし名称変更するなら早めにIssue立てた方がいいかなって思ったのもあって、無知に色々と雑にIssueを立ててしまいましたが、こういったルールをとるものもあるんですね。

**Comment by kzrnm** [comment]
パスカルケースに変更済みなのでclose
