### ISSUE TITLE
このリポジトリの今後の方針について

### ISSUE THREAD

**Issue by key-moon** [kzrnm/ac-library-csharp#72]
現状、このリポジトリは実質的にメンテナンスが不在の状況となっています。これは偏に私が無責任にもメンテナンスを放置してしまったためです。まず、これについて深くお詫び致します。

このままの状態としておくのは誰にとっても良くないことであると考えます。ですので、このリポジトリをどのようにするべきかの方針を相談したく思います。
現状では、このリポジトリのフォークである [kzrnm/ac-library-csharp](https://github.com/kzrnm/ac-library-csharp)（以下フォークと呼ぶ）が @kzrnm さんによって精力的に開発されています。ですので、このコードベースをメインとして活用させて頂けるのであれば、それが望ましいと考えます。
これを基に、以下の 3 つを今後の方針として提案します。

1. このリポジトリにフォークをマージする
2. このリポジトリにフォークをマージした上で、リポジトリ自体を [GitHub の機能](https://docs.github.com/ja/repositories/creating-and-managing-repositories/transferring-a-repository)を用いて移譲する
3. このリポジトリをアーカイブし、フォークの使用及びコミットを README.md で促す

私は 3 の手法を推奨したいです。なぜならば、フォークには既に issue や PR 等のリポジトリ外の資産が多く溜まっていて、1 及び 2 の手法ではそれが失われるからです。
もし @kzrnm さんに承諾頂けるのであれば、そのようにさせていただこうと思っています。また、これ以外の方法を提案いただいても構いません。

繰り返しとなりますが、ご迷惑をおかけしてしまい申し訳ありません。

**Comment by kzrnm** [comment]
@key-moon フォークの関係もあるので2の移譲の方が個人的にはありがたいです。
その場合、マージしてからの移譲より、移譲後にこちらで[ac-library-csharp](https://github.com/kzrnm/ac-library-csharp) のマージやissue や PR の整理を行う方が助かります。

**Comment by key-moon** [comment]
@kzrnm わかりました。ただ、まだ試したわけではないですが、ドキュメントには

> ターゲットのアカウントは、同じ名前のリポジトリを持っていたり、同じネットワーク内にフォークを持っていたりしてはなりません。

とあるため、フォークを削除して頂かない限り現状のまま移譲することは難しいと考えていました。

なお、コラボレーターとしてリポジトリへのアクセス権限を追加すれば同等のことが可能かと思います。

**Comment by kzrnm** [comment]
@key-moon  フォークがあるとダメそうだったので [ac-library-csharp](https://github.com/kzrnm/ac-library-csharp) をサブアカウントに移しました。
これで移管可能になったかと思います。

**Comment by kzrnm** [comment]
@key-moon 移管済みました。

Collaborator としては残っておきますか？
それともこれも外したほうが良いでしょうか？

**Comment by key-moon** [comment]
@kzrnm ありがとうございます。Collaborator についてはお任せしますが、個人的には外した方が好ましいかと思います。

**Comment by kzrnm** [comment]
@key-moon わかりました。外しておきました。
